### PR TITLE
feat: add docs overview page

### PR DESCRIPTION
**Pull request by hugorut**
* Adds cicd overview page with list of supported integrations (see screenshot for current look with logos)
* Removes legacy "other supported ci/cd" page, adds redirect
* Removes github, gitlab, atlantis, azure items from sidebar (currently keeps the page around, but we can nuke and add a redirect to "overview" page if desired) and favours sending users directly to the README of those integrations
* Adds Docker Images page with tweaked instructions - added to sidebar
* Adds standalone Slack page, extracted out of "other ci/cd" page - no sidebar

Screenshot 2022-02-17 at 14 11 49

### CODE REVIEW

**Comment by hugorut** [comment]
@alikhajeh1 man it was a pain to get some of these logos the way we discussed (e.g. Gitlab -> Gitlab CI, bitbucket -> bitbucket pipelines). Most of these providers don't have standalone logos for these platforms so I had to mock them with the closest font face I could find, It was fiddly.

**Comment by hugorut** [comment]
Converting to draft as @aliscott has some thoughts and think it would be best to discuss with him before we make the final changes to delete pages and migrate text e.t.c

**Comment by alikhajeh1** [comment]
Thanks @hugorut - this was simply awesome. I've pushed a commit with the changes we discussed and have merged it manually to master.

**Comment by hugorut** [comment]
@alikhajeh1 ❤️

**Pull request merged**
