### PR TITLE
Add docs for self-signed certificates

### PR DESCRIPTION
**Pull request by aliscott**

### CODE REVIEW

**Review by alikhajeh1 — APPROVED** [review]
LGTM!
We should add the env to https://www.infracost.io/docs/integrations/environment_variables/
Should we mention this in https://github.com/infracost/cloud-pricing-api - seems like most users who are testing it from their CI/CD will need it?

**Comment by aliscott** [comment]
> We should add the env to https://www.infracost.io/docs/integrations/environment_variables/

We don't currently mention the self-hosting `INFRACOST_PRICING_API_ENDPOINT` env var in there, so if we want to add these to there maybe we should add a section for self-hosting?

> Should we mention this in https://github.com/infracost/cloud-pricing-api 
👍  will create a PR for this

**Comment by aliscott** [comment]
Added PR for CPAPI: https://github.com/infracost/cloud-pricing-api/pull/133

**Comment by alikhajeh1** [comment]
Good point - this is fine.

**Pull request merged**
